# Generated by Django 5.0.1 on 2024-03-02 09:04

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('sku', models.CharField(max_length=50, validators=[utils.validators.SKUValidator()], verbose_name='Stock keeping unit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('avatar', models.ImageField(blank=True, upload_to='packages/', verbose_name='Avatar')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Is enable')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='Updated time')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='Expire time')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='subscriptions.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
    ]
