# Generated by Django 5.0.1 on 2024-02-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('avatar', models.ImageField(blank=True, upload_to='categories/', verbose_name='Avatar')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Is_enable')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_time')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='Updated_time')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('avatar', models.ImageField(blank=True, upload_to='products/', verbose_name='Avatar')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_time')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='Updated_time')),
                ('categories', models.ManyToManyField(blank=True, to='products.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Is_enable')),
                ('file_type', models.PositiveSmallIntegerField(choices=[(1, 'Audio'), (2, 'Video'), (3, 'Picture')], default=3, verbose_name='File_type')),
                ('file', models.FileField(upload_to='files/%y/%m/%d', verbose_name='File')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_time')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='Updated_time')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'files',
                'db_table': 'files',
            },
        ),
    ]
